version: '3.8'

services:
  app:
    container_name: feeling-memory-app
    build: .
    depends_on:
      - db
    image: maristadev/feeling-memory-app:staging
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAKAO_OAUTH_CLIENT_ID: ${KAKAO_OAUTH_CLIENT_ID}
      KAKAO_OAUTH_CLIENT_SECRET: ${KAKAO_OAUTH_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${STAGING_GOOGLE_REDIRECT_URI}
      AWS_ACCESS_KEY: ${STAGING_AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${STAGING_AWS_SECRET_KEY}
    ports:
      - "80:8080"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: feeling-memory-database
    environment:
      MYSQL_DATABASE: feeling_memory
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always