package com.fivefeeling.memory.domain.notification.model;

public enum NotificationType {
  SHARED_REQUEST,
  SHARED_APPROVE,
  SHARED_REJECTED,
  TRIP_UPDATED,
  TRIP_DELETED,
  MEDIA_FILE_ADDED,
  MEDIA_FILE_UPDATED,
  MEDIA_FILE_LOCATION_UPDATED,
  MEDIA_FILE_DELETED,
  TRIP_UPDATED_BY_COLLABORATOR,
  MEDIA_FILE_ADDED_BY_COLLABORATOR,
  MEDIA_FILE_LOCATION_UPDATED_BY_COLLABORATOR,
  MEDIA_FILE_UPDATED_BY_COLLABORATOR,
  MEDIA_FILE_DELETED_BY_COLLABORATOR
}
